CREATE TABLE clientes (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome       VARCHAR2(100) NOT NULL,
    cpf        VARCHAR2(11) NOT NULL,
    email      VARCHAR2(150),
    cidade     VARCHAR2(100),
    estado     CHAR(2),
    data_cadastro DATE DEFAULT SYSDATE,

    CONSTRAINT pk_clientes
        PRIMARY KEY (id_cliente)
);

CREATE TABLE produtos (
    id_produto NUMBER GENERATED BY DEFAULT AS IDENTITY,
    descricao  VARCHAR2(150) NOT NULL,
    categoria  VARCHAR2(100),
    preco      NUMBER(10,2) NOT NULL,

    CONSTRAINT pk_produtos
        PRIMARY KEY (id_produto)
);

CREATE TABLE pedidos (
    id_pedido NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cliente NUMBER NOT NULL,
    data_pedido DATE DEFAULT SYSDATE,
    status VARCHAR2(20),
    valor_total NUMBER(12,2),

    CONSTRAINT pk_pedidos
        PRIMARY KEY (id_pedido),

    CONSTRAINT fk_pedidos_clientes
        FOREIGN KEY (id_cliente)
        REFERENCES clientes(id_cliente)
);

CREATE TABLE itens_pedido (
    id_item NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_pedido NUMBER NOT NULL,
    id_produto NUMBER NOT NULL,
    quantidade NUMBER NOT NULL,
    valor_unitario NUMBER(10,2),

    CONSTRAINT pk_itens_pedido
        PRIMARY KEY (id_item),

    CONSTRAINT fk_itens_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES pedidos(id_pedido),

    CONSTRAINT fk_itens_produto
        FOREIGN KEY (id_produto)
        REFERENCES produtos(id_produto)
);